### ISSUE TITLE
Live Stream Implementation 

### ISSUE THREAD

**Issue by StarChaser44** [rgreagle375/484-Group-1#2]
Active live stream with multiple users connected over WebRTC

**Comment by espiem** [comment]
A bit of research got me this : https://aws.amazon.com/kinesis/video-streams/

Looks like it's AWS's native streaming service which works with WebRTC. We should be able to build this completely with WebRTC

**Comment by StarChaser44** [comment]
Live streaming implemented, may be able to add some features over time like enabling audio. Although this will only  be implemented if time permits.
